version: '3.8'

services:
  app:
    container_name: rabbit_work_queues_sample
    build:
      context: .
      target: development
    ports:
      - "5005:5005"
    depends_on:
      rabbitmq:
        condition: service_healthy

  rabbitmq:
    container_name: rabbit_work_queues_sample_rabbitmq
    image: rabbitmq:3.10.1-management-alpine
#    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q status
      interval: 30s
      timeout: 30s
      retries: 3


